"""empty message

Revision ID: 1bef1ee4ee4e
Revises: 8205a111aef5
Create Date: 2017-06-09 14:37:42.215000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bef1ee4ee4e'
down_revision = '8205a111aef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('head_img', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'head_img')
    # ### end Alembic commands ###
