"""empty message

Revision ID: 483bb807498b
Revises: c6fa3b0ba5fe
Create Date: 2017-05-17 16:07:58.271000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483bb807498b'
down_revision = 'c6fa3b0ba5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('front_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('qq', sa.String(length=20), nullable=True),
    sa.Column('realname', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=100), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('front_user')
    # ### end Alembic commands ###
