"""empty message

Revision ID: 86fa4c258b00
Revises: 483bb807498b
Create Date: 2017-05-25 23:47:51.208000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86fa4c258b00'
down_revision = '483bb807498b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'front_user', ['telephone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'front_user', type_='unique')
    # ### end Alembic commands ###
