"""empty message

Revision ID: c6fa3b0ba5fe
Revises: e048918119da
Create Date: 2017-05-10 14:47:41.293000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fa3b0ba5fe'
down_revision = 'e048918119da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('cms_user', sa.Column('last_login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'last_login_time')
    op.drop_column('cms_user', 'is_active')
    # ### end Alembic commands ###
